### ISSUE TITLE
Multiplayer: Missing information on the scoreboard

### ISSUE THREAD

**Issue by aubanel** [Orange-OpenSource/super-coding-ball#1]
I've been playing a few days in a row, and I felt that somethings were amiss in the scoreboard:
For each competitor, visualize 

- the status for today: not played / won +2 / lost +0 / draw +1 (even better with the score). This is kind of annoying, as you have to either remember who you have already played against or click to see what the dialog is saying. As the list grows it gets more difficult.
- number of days since last played game, total number of days ever played, date of last change in their code, code size
- could even grow the statistics with total number of matches played, total number of matches replayed, total number of won/lost/draw, numbers of changes made to the code, etc.

**Comment by clementcontet** [comment]
Hi and thanks for playing that much!

I'm not that into statistics: I want the UX to be minimalist to be understood easily by teenagers (and readable on mobile).
But you're right about the missing status of the daily games: it's a pain for heavy players.
I'm adding it right now! (with the "cup" icon already used for the offline game, it shouldn't be too difficult to understand)

**Comment by aubanel** [comment]
Just tested it, it's great. Thanks !
