### ISSUE TITLE
Feature request: highlight active instructions

### ISSUE THREAD

**Issue by aubanel** [Orange-OpenSource/super-coding-ball#2]
While playing the match, to analyze what is going on, it would be helpful to have a frame (one per player - find ways to differentiate them visually) highlighting the executed instruction in the current cycle. A nice plus would be to be able to pause the game as 4 frames might be a bit difficult to follow in real time

**Comment by clementcontet** [comment]
Hi,
The idea is indeed interesting but I don't think it is compatible with SuperCodingBall:
* it would work in a "step by step" debugger (like in https://google.github.io/blockly-samples/examples/interpreter-demo/step-execution.html) but not in the realtime game: the blocks are interpreted 20+ times per second, it would be totally unsuable (even more if we split the programming area in 4 for the 4 players)
* the UX aims to be "mobile first" (target is 10+ kids who mainly play on a smartphone) and the blocks are not shown alongside the game field on mobile

**Comment by aubanel** [comment]
- As you have a fast play button, you could have a normal play and a slow play, instead of running a 20Hz you wold run at 2 Hz (alternatively could just be a speed control). If you get crazy you can add a pause button and a step control to jump 1 / 10 / 100 / n cycles
- I guess I'm not fitting in the target then ^^ However, as your algorithm grows in complexity, keeping everything in mind to adapt it to situation you discover in match gets difficult. What about a way to slide between the match and the code on mobile apps ? I understand this is quite a heavy change though.

**Comment by clementcontet** [comment]
> I guess I'm not fitting in the target then ^^

Yes, adding a debugger and showing the blocks alongside the game field on mobile would add way too much complexity to the UX that I want to keep minimalist, and for a functionality that most users wouldn't even use.

Sorry!

**Comment by clementcontet** [comment]
Implemeted with https://github.com/Orange-OpenSource/super-coding-ball/commit/6e5a66c0aa8b473cd632e5adb319b7e0e88951fb
