### ISSUE TITLE
Feature Suggestion: Score as a condition

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#22]
Maybe it could be interesting to have access to the current score (or score delta, or is you are currently "leading" "equal" "losing").

Your team strategy and behavior could be different depending if you are on the winning edge or on the losing edge. Like trying to be more defensive when you are winning and be more aggressive when you are losing. This seems to be how real football team behave. :-) 

This could be as simple as 3 conditions without any need for math on the score.

PS: Thank you for this game, it is really fun.

**Comment by clementcontet** [comment]
Great idea! I'll look into that.
In the same way, it could also be interesting to add the current time position.

**Comment by clementcontet** [comment]
Implemented in 22e7c26
