### ISSUE TITLE
Feature Suggestion: Self-defined target position of players

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#23]
Yet another Feature Suggestion...

I would be interested to be able to customize the target position of each player before the match start. This is mostly because the current defender position are a bit too low for my strategy.

To implement this I would suggest an new start block that say:
"When the game is about to start"

And a set "target position" block that say:
Set role (attacker|defender) side (right|left) to [POSITION_BLOCK].
And to use that you would put an instance of the existing POSITION_BLOCK that is (A|B|C|D|E)(1|2|3|4|5)

Of course if you don't use those block, you get the default value.

You could even imagine to change the target position during the match, like at a certain time or score (see #22). You could then play higher or lower depending if you are losing or wining.

It is just an idea, great if you find that great, fine of you are not interested.

**Comment by clementcontet** [comment]
Thanks for this new suggestion but I think this one would be too complex for the users (audience is 10+ kids).
For now, you have to set one and only one action for each of the 4 events (to enforce that, you can't stack anything below an action or a condition).

Adding a 5th event  "when the game starts" that is not related to actions, and a new (stackable) statement "set target position to..." that is not an action would make it harder to understand the game basics. And you would have to introduce loops to change positions at certain time or score.

For advanced users, you can still do what you want with the current blocks:
![image](https://user-images.githubusercontent.com/7261426/237040782-5b4a9d7c-7072-40ac-ada8-8b089467d5ad.png)

**Comment by dglaude** [comment]
Perfectly fair.
Thank you.
