### ISSUE TITLE
Online play has two change time, midnight and ??? (was stopped working on 1st June 2023 at 0:00)

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#24]
Hi,

As I frequently do, I played at the end of the day (before Midnight Paris time).
And if I pass midnight, this is another day, and all my match get reset to grey as a new day start.
Then a bit later, the player that did not play since 16(?) days disapear.

But today (01/06/2023) the list of opponent became empty.

Best regards.

**Comment by dglaude** [comment]
The list of player was coming empty last night, at least from midnight to 1H30 AM (maybe more). Is it working now.
In the past I already notices some de-sync between midnight where the result are reset (but maybe that is javascript activities in the browser) and later in the night where player not active are removed (and that could be a server side decision).
My assumption was that the cleaning of player is around 2AM (Paris time).
So possibly, that process did auto-repear the online player list...
But I clearly remember having play between midnight and 2AM without any problem.

**Comment by clementcontet** [comment]
Hi, I use a serverless database (Webcom) so there is no code running on any server.
The cleaning of outdated players is made by the first player that connects online and detects them.
But if you have recurring bugs between midnight Paris time, and 02:00 Paris time (= midnight GMT), I may have a bug with days management.

**Comment by dglaude** [comment]
I'll try again another night.

I don't really have problem (except during the night between 31-05 and 01-06 where the list was empty).
But I can see discrepancy in score table in the early hours of the morning.
Not everything seems to occurs at midnight, but it is no big deal.

**Comment by dglaude** [comment]
I have print to pdf score board at:
[SuperCodingBall_20230602_0730.pdf](https://github.com/Orange-OpenSource/super-coding-ball/files/11632208/SuperCodingBall_20230602_0730.pdf)
[SuperCodingBall_20230602_0127.pdf](https://github.com/Orange-OpenSource/super-coding-ball/files/11632209/SuperCodingBall_20230602_0127.pdf)
[SuperCodingBall_20230602_0001.pdf](https://github.com/Orange-OpenSource/super-coding-ball/files/11632210/SuperCodingBall_20230602_0001.pdf)

It show that at Midnight all the opponent turn to grey (at 00:01) and the number of player is 77.
At 01:27 I have accumulated points, and there are still 77 players.
At 07:30 I have less points and there are only 75 players.

So for me the cleaning take place in two steps, one at midnight and maybe one at 2AM.
Because I think I already noticed something one day.
But I could not stay up that late tonight.

It could make sense that the cleaning of win and loss occurs in local time for the player (imagine someone in Australia), but that the cleaning of non playing player and score from 16 days ago occurs on midnight UTC (or something like that).
It does not explain the bug I had the other night... that I confirmed in two browser and with multiple refresh.

**Comment by clementcontet** [comment]
You're right, after reviewing the code:
- the deletion of games older than 15 days is done by the first player who connects after midnight UTC (whatever their region in the world, the rule is the same for all players) => https://github.com/Orange-OpenSource/super-coding-ball/blob/2c1f04c03b48440e3e913fe1ac75de4e83e5e56c/src/app/services/online.service.ts#L186-L187
- the reset of daily scores is done at midnight local time (as you said, it wouldn't make sense to reset scores at noon for people in Australia) => https://github.com/Orange-OpenSource/super-coding-ball/blob/2c1f04c03b48440e3e913fe1ac75de4e83e5e56c/src/app/components/online-opponents/online-opponents.component.ts#L115

The bug you experienced seems like a temporary downtime in Webcom.
If you don't encounter it again, I'll close the issue.
