### ISSUE TITLE
Feature request: Play against computer to behave like online play..

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#25]
Hi,

I have a feature suggestion for the "Play against computer".
Currently, once you have win against one of the pre-defined strategy, it stay a win for ever.
This mean that if you want to try a new strategy, you need to remember your score against all the opponent.
It is not visible what opponent  you already played against.

A few possible fixe:
a) Only show the result for the last 24 hours or from current day, so every day you can try against with a different team strategy and visualize the whole result. So the title of the column would be "Won today?"
b) Display your last result against each opponent, a bit like for on the online (so you can improve by playing multiple time). So the column would move from "Won?" to "Last Match Result". And you can have that and the behavior describe in (a).
c) Have a button to forget about all the result, and just grey all the opponent, the same state as it was when you first play.

More advanced and interesting option... integrate the "Play against computer" into the "Play online". Have those opponent and strategy always available as opponent in the "Play online". Could be with a special name "AI: All players in defense". That way from one same interface, you would have those same opponent you can prepare against, but your score against those will count.
Automatically, all the behavour of "Play online" will be present for remembering how you did today against those opponent.
Those strategy or team would be ranked and we could see how they behave compare to human player.

Thanks in advance

**Comment by clementcontet** [comment]
Hi, I want to keep offline and online separated (offline is playable without account and even without Internet) and keep online available to people with at least 3 offline wins.
But I keep the idea and will integrate it as a "delete everything on this device" button (i.e. offline wins, strategy and local information about the account).
It can be usefull in a classroom or public computer context, and it will mostly answer your needs (you'll only have to reconnect to your account and re-download your strategy)

**Comment by clementcontet** [comment]
Added "remove all data" button in privacy page:
https://github.com/Orange-OpenSource/super-coding-ball/commit/23c458fb76dc5cda50765dc4cc6ca4423f43be59
