### ISSUE TITLE
Feature request: Display last score in "Play Online"

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#26]
Hi,

I have a feature suggestion for the "Play Online".

In addition to remembering and displaying with a colour if you already played against that opponent, and if the game was a win/draw/loss...
You could remember and display the last score against that player.
Winning by 5-0 or wining with a 2-1 is not the same, 2-1 mean you could have been lucky but another match will give another result.
Also wining x-0 indicate you have a good defense, where a non zero mean you have some weakness in defense.
Having the score visible could help see what opponent are more interesting to try to improve against.

Thanks in advance for considering this feature.

**Comment by clementcontet** [comment]
Hi, sorry, that's a too advanced feature for the basic UX/functionnalities I want to keep in the app! (most students just want to get more points and don't care about the scores)
