### ISSUE TITLE
Recovering your team when changing browser (without playing against Computer)

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#27]
Hi,

Sometime ago, I wanted to continue playing on my phone what I started to play on a desktop.
The idea was to log in with the same Google or Facebook account and continue from there.
However, access to "Play online!" requires that you first create a team and "You must first beat at least 3 computer teams before playing online!".

Only then you can go on "Play online!" and login to recover your team... and you to be careful not to overwrite your server side team with your local new team (the one you created to get access to "Play online!".

So I guess to solve this problem, you need to have the login button on the front page, and going that path, your recover your team just by connecting with the same Google or Facebook account.

But I understand you want to continue enforce that user first train against the computer before playing against other humans.

Than you in advance for considering this problem.

**Comment by clementcontet** [comment]
Hi, other people have asked this before but my main objection is that the app should remain usable offline (when downloaded as a PWA on mobile).
So you have to be able to play against the computer without connecting to any account first.

I understand that it is a bit longer to play online on a new device, but I figured out that beating 3 computer teams is not that long!
