### ISSUE TITLE
Feature request: Explicit no operation action

### ISSUE THREAD

**Issue by dglaude** [Orange-OpenSource/super-coding-ball#29]
Hi,

I don't think there is an explicit "do nothing" or "rest" or "hold position" block.
I guess if you put nothing in your block structure, your player will do nothing if it reach that point.
But that look a bit like your program is missing a piece or under construction.

I was wondering if there would be an interest in having a block for that.
One of the goal could be to somehow recover energy for your player.
Or is there a recommended way to do that? "run to (myself)"

Regards

**Comment by clementcontet** [comment]
Hi, indeed when a player's strategy has no block in a branch, or when he is running towards a target that is close enough, he is still and recovers energy (some users do this to keep players as goal keepers).
It may seem visually as a hole in the strategy, but I think it would be more confusing to add a block that does nothing.

**Comment by dglaude** [comment]
That is what I was thinking about name such as "rest" that can relate to "recovering energy".
But it is fine as it is now.
